// Code generated by protoc-gen-go.
// source: github.com/ashwinsr/auctions/common_pb/common.proto
// DO NOT EDIT!

/*
Package common_pb is a generated protocol buffer package.

It is generated from these files:
	github.com/ashwinsr/auctions/common_pb/common.proto

It has these top-level messages:
	OuterStruct
	Key
	DiscreteLogKnowledge
	EqualsOneOfTwo
	VerifiableShuffle
	DiscreteLogEquality
*/
package common_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OuterStruct struct {
	Clientid int32  `protobuf:"varint,1,opt,name=clientid" json:"clientid,omitempty"`
	Stepid   int32  `protobuf:"varint,2,opt,name=stepid" json:"stepid,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *OuterStruct) Reset()                    { *m = OuterStruct{} }
func (m *OuterStruct) String() string            { return proto.CompactTextString(m) }
func (*OuterStruct) ProtoMessage()               {}
func (*OuterStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The request message containing the user's name.
type Key struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Zero knowledge proof of key's logarithm
	Proof *DiscreteLogKnowledge `protobuf:"bytes,2,opt,name=proof" json:"proof,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Key) GetProof() *DiscreteLogKnowledge {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DiscreteLogKnowledge struct {
	T []byte `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogKnowledge) Reset()                    { *m = DiscreteLogKnowledge{} }
func (m *DiscreteLogKnowledge) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogKnowledge) ProtoMessage()               {}
func (*DiscreteLogKnowledge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EqualsOneOfTwo struct {
	A_1 []byte `protobuf:"bytes,1,opt,name=a_1,json=a1,proto3" json:"a_1,omitempty"`
	A_2 []byte `protobuf:"bytes,2,opt,name=a_2,json=a2,proto3" json:"a_2,omitempty"`
	B_1 []byte `protobuf:"bytes,3,opt,name=b_1,json=b1,proto3" json:"b_1,omitempty"`
	B_2 []byte `protobuf:"bytes,4,opt,name=b_2,json=b2,proto3" json:"b_2,omitempty"`
	D_1 []byte `protobuf:"bytes,5,opt,name=d_1,json=d1,proto3" json:"d_1,omitempty"`
	D_2 []byte `protobuf:"bytes,6,opt,name=d_2,json=d2,proto3" json:"d_2,omitempty"`
	R_1 []byte `protobuf:"bytes,7,opt,name=r_1,json=r1,proto3" json:"r_1,omitempty"`
	R_2 []byte `protobuf:"bytes,8,opt,name=r_2,json=r2,proto3" json:"r_2,omitempty"`
}

func (m *EqualsOneOfTwo) Reset()                    { *m = EqualsOneOfTwo{} }
func (m *EqualsOneOfTwo) String() string            { return proto.CompactTextString(m) }
func (*EqualsOneOfTwo) ProtoMessage()               {}
func (*EqualsOneOfTwo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type VerifiableShuffle struct {
}

func (m *VerifiableShuffle) Reset()                    { *m = VerifiableShuffle{} }
func (m *VerifiableShuffle) String() string            { return proto.CompactTextString(m) }
func (*VerifiableShuffle) ProtoMessage()               {}
func (*VerifiableShuffle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DiscreteLogEquality struct {
	Ts [][]byte `protobuf:"bytes,1,rep,name=ts,proto3" json:"ts,omitempty"`
	R  []byte   `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogEquality) Reset()                    { *m = DiscreteLogEquality{} }
func (m *DiscreteLogEquality) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogEquality) ProtoMessage()               {}
func (*DiscreteLogEquality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*OuterStruct)(nil), "common_pb.OuterStruct")
	proto.RegisterType((*Key)(nil), "common_pb.Key")
	proto.RegisterType((*DiscreteLogKnowledge)(nil), "common_pb.DiscreteLogKnowledge")
	proto.RegisterType((*EqualsOneOfTwo)(nil), "common_pb.EqualsOneOfTwo")
	proto.RegisterType((*VerifiableShuffle)(nil), "common_pb.VerifiableShuffle")
	proto.RegisterType((*DiscreteLogEquality)(nil), "common_pb.DiscreteLogEquality")
}

func init() {
	proto.RegisterFile("github.com/ashwinsr/auctions/common_pb/common.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x6b, 0xe3, 0x30,
	0x10, 0x85, 0x91, 0x9d, 0x64, 0xb3, 0x8a, 0xc9, 0xee, 0x2a, 0xcb, 0x22, 0xf6, 0xd2, 0xe0, 0x53,
	0x4e, 0x0e, 0x52, 0xe8, 0x3f, 0x68, 0x4f, 0x29, 0x0d, 0x38, 0x6d, 0xaf, 0x46, 0xb6, 0xe5, 0x44,
	0xd4, 0xb1, 0x5c, 0x69, 0x4c, 0xc8, 0x3f, 0xe9, 0xcf, 0x2d, 0x96, 0x45, 0x68, 0xa1, 0xb7, 0x99,
	0x4f, 0xef, 0x3d, 0xe6, 0x21, 0xbc, 0x39, 0x28, 0x38, 0x76, 0x79, 0x52, 0xe8, 0xd3, 0x5a, 0xd8,
	0xe3, 0x59, 0x35, 0xd6, 0xac, 0x45, 0x57, 0x80, 0xd2, 0x8d, 0x5d, 0x17, 0xfa, 0x74, 0xd2, 0x4d,
	0xd6, 0xe6, 0x7e, 0x4a, 0x5a, 0xa3, 0x41, 0x93, 0x9f, 0x57, 0x1e, 0x3f, 0xe3, 0xd9, 0xae, 0x03,
	0x69, 0xf6, 0x60, 0xba, 0x02, 0xc8, 0x7f, 0x3c, 0x2d, 0x6a, 0x25, 0x1b, 0x50, 0x25, 0x45, 0x4b,
	0xb4, 0x1a, 0xa7, 0xd7, 0x9d, 0xfc, 0xc3, 0x13, 0x0b, 0xb2, 0x55, 0x25, 0x0d, 0xdc, 0x8b, 0xdf,
	0x08, 0xc1, 0xa3, 0x52, 0x80, 0xa0, 0xe1, 0x12, 0xad, 0xa2, 0xd4, 0xcd, 0xf1, 0x23, 0x0e, 0xb7,
	0xf2, 0x42, 0x7e, 0xe3, 0xf0, 0x55, 0x5e, 0x5c, 0x52, 0x94, 0xf6, 0x23, 0xb9, 0xc5, 0xe3, 0xd6,
	0x68, 0x5d, 0xb9, 0x8c, 0x19, 0xbf, 0x49, 0xae, 0xa7, 0x24, 0x77, 0xca, 0x16, 0x46, 0x82, 0x7c,
	0xd0, 0x87, 0x6d, 0xa3, 0xcf, 0xb5, 0x2c, 0x0f, 0x32, 0x1d, 0xd4, 0x31, 0xc7, 0x7f, 0xbf, 0x7b,
	0x26, 0x11, 0x46, 0xe0, 0xe3, 0x11, 0xf4, 0x9b, 0x71, 0xc1, 0x51, 0x8a, 0x4c, 0xfc, 0x8e, 0xf0,
	0xfc, 0xfe, 0xad, 0x13, 0xb5, 0xdd, 0x35, 0x72, 0x57, 0x3d, 0x9d, 0x35, 0xf9, 0x85, 0x43, 0x91,
	0x31, 0x6f, 0x08, 0x04, 0x1b, 0x00, 0xf7, 0x9e, 0x40, 0xf0, 0x1e, 0xe4, 0x19, 0xf3, 0x5d, 0x82,
	0x9c, 0x0d, 0x80, 0xd3, 0x91, 0x07, 0x4e, 0x51, 0x66, 0x8c, 0x8e, 0x07, 0x50, 0xb2, 0x01, 0x70,
	0x3a, 0xf1, 0xc0, 0x29, 0x4c, 0xc6, 0xe8, 0x8f, 0x01, 0x18, 0x36, 0x00, 0x4e, 0xa7, 0x1e, 0xf0,
	0x78, 0x81, 0xff, 0xbc, 0x48, 0xa3, 0x2a, 0x25, 0xf2, 0x5a, 0xee, 0x8f, 0x5d, 0x55, 0xd5, 0x32,
	0xde, 0xe0, 0xc5, 0xa7, 0x8e, 0xee, 0x72, 0x05, 0x17, 0x32, 0xc7, 0x01, 0x58, 0x8a, 0x96, 0x61,
	0xef, 0x05, 0xfb, 0xb5, 0x64, 0x3e, 0x71, 0x3f, 0xba, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0x9e, 0x75, 0x68, 0x08, 0x02, 0x00, 0x00,
}
