// Code generated by protoc-gen-go.
// source: comm.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	comm.proto

It has these top-level messages:
	Key
	DiscreteLogKnowledge
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Key struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Zero knowledge proof of key's logarithm
	Proof *DiscreteLogKnowledge `protobuf:"bytes,2,opt,name=proof" json:"proof,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Key) GetProof() *DiscreteLogKnowledge {
	if m != nil {
		return m.Proof
	}
	return nil
}

type DiscreteLogKnowledge struct {
	T []byte `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogKnowledge) Reset()                    { *m = DiscreteLogKnowledge{} }
func (m *DiscreteLogKnowledge) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogKnowledge) ProtoMessage()               {}
func (*DiscreteLogKnowledge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*DiscreteLogKnowledge)(nil), "pb.DiscreteLogKnowledge")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ZKPAuction service

type ZKPAuctionClient interface {
	// Sends a key
	SendKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type zKPAuctionClient struct {
	cc *grpc.ClientConn
}

func NewZKPAuctionClient(cc *grpc.ClientConn) ZKPAuctionClient {
	return &zKPAuctionClient{cc}
}

func (c *zKPAuctionClient) SendKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/SendKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZKPAuction service

type ZKPAuctionServer interface {
	// Sends a key
	SendKey(context.Context, *Key) (*google_protobuf.Empty, error)
}

func RegisterZKPAuctionServer(s *grpc.Server, srv ZKPAuctionServer) {
	s.RegisterService(&_ZKPAuction_serviceDesc, srv)
}

func _ZKPAuction_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/SendKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).SendKey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZKPAuction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ZKPAuction",
	HandlerType: (*ZKPAuctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendKey",
			Handler:    _ZKPAuction_SendKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0xcf, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x92, 0x4e, 0xcf, 0xcf, 0x4f,
	0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54, 0x42, 0x14,
	0x28, 0xb9, 0x73, 0x31, 0x7b, 0xa7, 0x56, 0x0a, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0x98, 0x42, 0x7a, 0x5c, 0xac, 0x40, 0x15, 0xf9, 0x69, 0x12,
	0x4c, 0x40, 0x31, 0x6e, 0x23, 0x09, 0xbd, 0x82, 0x24, 0x3d, 0x97, 0xcc, 0xe2, 0xe4, 0xa2, 0xd4,
	0x92, 0x54, 0x9f, 0xfc, 0x74, 0xef, 0xbc, 0xfc, 0xf2, 0x9c, 0xd4, 0x94, 0xf4, 0xd4, 0x20, 0x88,
	0x32, 0x25, 0x23, 0x2e, 0x11, 0x6c, 0xd2, 0x42, 0x3c, 0x5c, 0x8c, 0x25, 0x50, 0x73, 0x19, 0x4b,
	0x40, 0xbc, 0x22, 0xb0, 0x89, 0x40, 0x5e, 0x91, 0x91, 0x15, 0x17, 0x57, 0x94, 0x77, 0x80, 0x63,
	0x69, 0x72, 0x49, 0x66, 0x7e, 0x9e, 0x90, 0x0e, 0x17, 0x7b, 0x70, 0x6a, 0x5e, 0x0a, 0xc8, 0x39,
	0xec, 0x20, 0xdb, 0x80, 0x0c, 0x29, 0x31, 0x3d, 0x88, 0xe3, 0xf5, 0x60, 0x8e, 0xd7, 0x73, 0x05,
	0x39, 0x5e, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xba,
	0xcf, 0x63, 0xee, 0x00, 0x00, 0x00,
}
