// Code generated by protoc-gen-go.
// source: github.com/ashwinsr/auctions/first_price/first_price.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	github.com/ashwinsr/auctions/first_price/first_price.proto

It has these top-level messages:
	Round1
	Round2
	Gammas
	Deltas
	DiscreteLogEqualityProofs
	Round3
	Phis
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import common_pb "github.com/ashwinsr/auctions/common_pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Round1 struct {
	Alphas [][]byte                       `protobuf:"bytes,1,rep,name=alphas,proto3" json:"alphas,omitempty"`
	Betas  [][]byte                       `protobuf:"bytes,2,rep,name=betas,proto3" json:"betas,omitempty"`
	Proofs []*common_pb.EqualsOneOfTwo    `protobuf:"bytes,3,rep,name=proofs" json:"proofs,omitempty"`
	Proof  *common_pb.DiscreteLogEquality `protobuf:"bytes,4,opt,name=proof" json:"proof,omitempty"`
}

func (m *Round1) Reset()                    { *m = Round1{} }
func (m *Round1) String() string            { return proto.CompactTextString(m) }
func (*Round1) ProtoMessage()               {}
func (*Round1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Round1) GetProofs() []*common_pb.EqualsOneOfTwo {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func (m *Round1) GetProof() *common_pb.DiscreteLogEquality {
	if m != nil {
		return m.Proof
	}
	return nil
}

type Round2 struct {
	DoubleGammas []*Gammas                    `protobuf:"bytes,1,rep,name=doubleGammas" json:"doubleGammas,omitempty"`
	DoubleDeltas []*Deltas                    `protobuf:"bytes,2,rep,name=doubleDeltas" json:"doubleDeltas,omitempty"`
	DoubleProofs []*DiscreteLogEqualityProofs `protobuf:"bytes,3,rep,name=doubleProofs" json:"doubleProofs,omitempty"`
}

func (m *Round2) Reset()                    { *m = Round2{} }
func (m *Round2) String() string            { return proto.CompactTextString(m) }
func (*Round2) ProtoMessage()               {}
func (*Round2) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Round2) GetDoubleGammas() []*Gammas {
	if m != nil {
		return m.DoubleGammas
	}
	return nil
}

func (m *Round2) GetDoubleDeltas() []*Deltas {
	if m != nil {
		return m.DoubleDeltas
	}
	return nil
}

func (m *Round2) GetDoubleProofs() []*DiscreteLogEqualityProofs {
	if m != nil {
		return m.DoubleProofs
	}
	return nil
}

type Gammas struct {
	Gammas [][]byte `protobuf:"bytes,1,rep,name=gammas,proto3" json:"gammas,omitempty"`
}

func (m *Gammas) Reset()                    { *m = Gammas{} }
func (m *Gammas) String() string            { return proto.CompactTextString(m) }
func (*Gammas) ProtoMessage()               {}
func (*Gammas) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Deltas struct {
	Deltas [][]byte `protobuf:"bytes,1,rep,name=deltas,proto3" json:"deltas,omitempty"`
}

func (m *Deltas) Reset()                    { *m = Deltas{} }
func (m *Deltas) String() string            { return proto.CompactTextString(m) }
func (*Deltas) ProtoMessage()               {}
func (*Deltas) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DiscreteLogEqualityProofs struct {
	Proofs []*common_pb.DiscreteLogEquality `protobuf:"bytes,1,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *DiscreteLogEqualityProofs) Reset()                    { *m = DiscreteLogEqualityProofs{} }
func (m *DiscreteLogEqualityProofs) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogEqualityProofs) ProtoMessage()               {}
func (*DiscreteLogEqualityProofs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DiscreteLogEqualityProofs) GetProofs() []*common_pb.DiscreteLogEquality {
	if m != nil {
		return m.Proofs
	}
	return nil
}

type Round3 struct {
	DoublePhis   []*Phis                      `protobuf:"bytes,1,rep,name=doublePhis" json:"doublePhis,omitempty"`
	DoubleProofs []*DiscreteLogEqualityProofs `protobuf:"bytes,2,rep,name=doubleProofs" json:"doubleProofs,omitempty"`
}

func (m *Round3) Reset()                    { *m = Round3{} }
func (m *Round3) String() string            { return proto.CompactTextString(m) }
func (*Round3) ProtoMessage()               {}
func (*Round3) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Round3) GetDoublePhis() []*Phis {
	if m != nil {
		return m.DoublePhis
	}
	return nil
}

func (m *Round3) GetDoubleProofs() []*DiscreteLogEqualityProofs {
	if m != nil {
		return m.DoubleProofs
	}
	return nil
}

type Phis struct {
	Phis [][]byte `protobuf:"bytes,1,rep,name=phis,proto3" json:"phis,omitempty"`
}

func (m *Phis) Reset()                    { *m = Phis{} }
func (m *Phis) String() string            { return proto.CompactTextString(m) }
func (*Phis) ProtoMessage()               {}
func (*Phis) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Round1)(nil), "main.Round1")
	proto.RegisterType((*Round2)(nil), "main.Round2")
	proto.RegisterType((*Gammas)(nil), "main.Gammas")
	proto.RegisterType((*Deltas)(nil), "main.Deltas")
	proto.RegisterType((*DiscreteLogEqualityProofs)(nil), "main.DiscreteLogEqualityProofs")
	proto.RegisterType((*Round3)(nil), "main.Round3")
	proto.RegisterType((*Phis)(nil), "main.Phis")
}

func init() {
	proto.RegisterFile("github.com/ashwinsr/auctions/first_price/first_price.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0x31, 0x6f, 0xf2, 0x30,
	0x10, 0x15, 0x10, 0x3c, 0x1c, 0x99, 0xac, 0x4f, 0x28, 0x30, 0x7c, 0x8d, 0x32, 0xa1, 0x0e, 0xa1,
	0x84, 0xaa, 0x43, 0xd7, 0x52, 0x75, 0xa9, 0x44, 0xe5, 0x76, 0x47, 0x4e, 0x30, 0xc4, 0x52, 0x12,
	0xa7, 0xb1, 0x23, 0xc4, 0xaf, 0xe9, 0x6f, 0xe8, 0x3f, 0xac, 0xb0, 0x1d, 0x08, 0x42, 0x6d, 0xa5,
	0x6e, 0x77, 0xe7, 0xf7, 0xee, 0xde, 0x7b, 0x32, 0xdc, 0x6f, 0xb9, 0x4a, 0xeb, 0x38, 0x4c, 0x44,
	0x3e, 0xa5, 0x32, 0xdd, 0xf1, 0x42, 0x56, 0x53, 0x5a, 0x27, 0x8a, 0x8b, 0x42, 0x4e, 0x37, 0xbc,
	0x92, 0x6a, 0x55, 0x56, 0x3c, 0x61, 0xed, 0x3a, 0x2c, 0x2b, 0xa1, 0x04, 0x76, 0x72, 0xca, 0x8b,
	0xf1, 0xfc, 0xc7, 0x0d, 0x89, 0xc8, 0x73, 0x51, 0xac, 0xca, 0xd8, 0x56, 0x86, 0x1a, 0x7c, 0x74,
	0x00, 0x11, 0x51, 0x17, 0xeb, 0x19, 0x1e, 0x02, 0xa2, 0x59, 0x99, 0x52, 0xe9, 0x75, 0xfc, 0xde,
	0xc4, 0x25, 0xb6, 0xc3, 0xff, 0xa0, 0x1f, 0x33, 0x45, 0xa5, 0xd7, 0xd5, 0x63, 0xd3, 0xe0, 0x19,
	0xa0, 0xb2, 0x12, 0x62, 0x23, 0xbd, 0x9e, 0xdf, 0x9b, 0x0c, 0xa2, 0x51, 0x78, 0xbc, 0x10, 0x3e,
	0xbe, 0xd7, 0x34, 0x93, 0xcb, 0x82, 0x2d, 0x37, 0x6f, 0x3b, 0x41, 0x2c, 0x10, 0xdf, 0x42, 0x5f,
	0x57, 0x9e, 0xe3, 0x77, 0x26, 0x83, 0xe8, 0x7f, 0x8b, 0xb1, 0xe0, 0x32, 0xa9, 0x98, 0x62, 0xcf,
	0x62, 0xab, 0xc9, 0x5c, 0xed, 0x89, 0x01, 0x07, 0x9f, 0x8d, 0xc2, 0x08, 0xdf, 0x80, 0xbb, 0x16,
	0x75, 0x9c, 0xb1, 0x27, 0x9a, 0xe7, 0x56, 0xe7, 0x20, 0x72, 0xc3, 0x83, 0xfd, 0xd0, 0xcc, 0xc8,
	0x19, 0xe2, 0xc4, 0x58, 0xb0, 0xac, 0xb1, 0x70, 0x64, 0x98, 0x19, 0x39, 0x43, 0xe0, 0x87, 0x86,
	0xf1, 0xd2, 0x76, 0x77, 0x65, 0x19, 0x97, 0x32, 0x0d, 0x8c, 0x9c, 0x91, 0x02, 0x1f, 0x90, 0x15,
	0x30, 0x04, 0xb4, 0x3d, 0x89, 0x75, 0x89, 0xed, 0x0e, 0x08, 0x7b, 0x70, 0x08, 0x68, 0x6d, 0xc4,
	0x59, 0x84, 0xe9, 0x82, 0x57, 0x18, 0x7d, 0x7b, 0x0e, 0xdf, 0x1d, 0xd3, 0x37, 0x19, 0xfc, 0x96,
	0xa5, 0x45, 0x07, 0x7b, 0x9b, 0xe5, 0x1c, 0x5f, 0x03, 0x58, 0xc9, 0x29, 0x6f, 0xb6, 0x80, 0x71,
	0x79, 0x98, 0x90, 0xd6, 0xeb, 0x45, 0x26, 0xdd, 0xbf, 0x64, 0x32, 0x06, 0x47, 0x2f, 0xc3, 0xe0,
	0x94, 0xcd, 0x49, 0x97, 0xe8, 0x3a, 0x46, 0xfa, 0x33, 0xce, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x1a, 0xe5, 0x77, 0x05, 0x03, 0x00, 0x00,
}
