package zkp

import (
	"math/big"
	"math/rand"
	"time"
)

const NumTests = 10

// FIXME need larger/dynamically generated
// FIXME should be generated by using jointly-generated random numbers
// FIXME as seeds to protocol-specified RNGs.
var P = big.NewInt(34531109)
var Q = big.NewInt(8632777)
var G = big.NewInt(19044154)

var Y_Mill = big.NewInt(19044154)
var K_Mill uint = 6

var Zero = big.NewInt(0)
var One = big.NewInt(1)
var Two = big.NewInt(2)
var Three = big.NewInt(3)
var FortyTwo = big.NewInt(42)

var Lt = big.NewInt(1024)
var Ls = big.NewInt(1024)
var Lr = big.NewInt(8632777) // Needs to be figured

// one RandGen per program ensures no duplicated random numbers
// FIXME in some cases like above, need to be jointly seeded
// by participants
var RandGen = rand.New(rand.NewSource(time.Now().UTC().UnixNano()))
