// Code generated by protoc-gen-go.
// source: comm.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	comm.proto

It has these top-level messages:
	Key
	AlphaBeta
	MixedOutput
	RandomizedOuput
	DiscreteLogKnowledge
	EqualsOneOfTwo
	VerifiableShuffle
	DiscreteLogEquality
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Key struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Zero knowledge proof of key's logarithm
	Proof *DiscreteLogKnowledge `protobuf:"bytes,2,opt,name=proof" json:"proof,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Key) GetProof() *DiscreteLogKnowledge {
	if m != nil {
		return m.Proof
	}
	return nil
}

// TODO millionaire specific
type AlphaBeta struct {
	Alphas [][]byte          `protobuf:"bytes,1,rep,name=alphas,proto3" json:"alphas,omitempty"`
	Betas  [][]byte          `protobuf:"bytes,2,rep,name=betas,proto3" json:"betas,omitempty"`
	Proofs []*EqualsOneOfTwo `protobuf:"bytes,3,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *AlphaBeta) Reset()                    { *m = AlphaBeta{} }
func (m *AlphaBeta) String() string            { return proto.CompactTextString(m) }
func (*AlphaBeta) ProtoMessage()               {}
func (*AlphaBeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AlphaBeta) GetProofs() []*EqualsOneOfTwo {
	if m != nil {
		return m.Proofs
	}
	return nil
}

// TODO millionaire specific
type MixedOutput struct {
	Gammas [][]byte           `protobuf:"bytes,1,rep,name=gammas,proto3" json:"gammas,omitempty"`
	Deltas [][]byte           `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	Proof  *VerifiableShuffle `protobuf:"bytes,3,opt,name=proof" json:"proof,omitempty"`
}

func (m *MixedOutput) Reset()                    { *m = MixedOutput{} }
func (m *MixedOutput) String() string            { return proto.CompactTextString(m) }
func (*MixedOutput) ProtoMessage()               {}
func (*MixedOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MixedOutput) GetProof() *VerifiableShuffle {
	if m != nil {
		return m.Proof
	}
	return nil
}

type RandomizedOuput struct {
	Gammas [][]byte               `protobuf:"bytes,1,rep,name=gammas,proto3" json:"gammas,omitempty"`
	Deltas [][]byte               `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	Proofs []*DiscreteLogEquality `protobuf:"bytes,3,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *RandomizedOuput) Reset()                    { *m = RandomizedOuput{} }
func (m *RandomizedOuput) String() string            { return proto.CompactTextString(m) }
func (*RandomizedOuput) ProtoMessage()               {}
func (*RandomizedOuput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RandomizedOuput) GetProofs() []*DiscreteLogEquality {
	if m != nil {
		return m.Proofs
	}
	return nil
}

type DiscreteLogKnowledge struct {
	T []byte `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogKnowledge) Reset()                    { *m = DiscreteLogKnowledge{} }
func (m *DiscreteLogKnowledge) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogKnowledge) ProtoMessage()               {}
func (*DiscreteLogKnowledge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type EqualsOneOfTwo struct {
	A_1 []byte `protobuf:"bytes,1,opt,name=a_1,json=a1,proto3" json:"a_1,omitempty"`
	A_2 []byte `protobuf:"bytes,2,opt,name=a_2,json=a2,proto3" json:"a_2,omitempty"`
	B_1 []byte `protobuf:"bytes,3,opt,name=b_1,json=b1,proto3" json:"b_1,omitempty"`
	B_2 []byte `protobuf:"bytes,4,opt,name=b_2,json=b2,proto3" json:"b_2,omitempty"`
	D_1 []byte `protobuf:"bytes,5,opt,name=d_1,json=d1,proto3" json:"d_1,omitempty"`
	D_2 []byte `protobuf:"bytes,6,opt,name=d_2,json=d2,proto3" json:"d_2,omitempty"`
	R_1 []byte `protobuf:"bytes,7,opt,name=r_1,json=r1,proto3" json:"r_1,omitempty"`
	R_2 []byte `protobuf:"bytes,8,opt,name=r_2,json=r2,proto3" json:"r_2,omitempty"`
}

func (m *EqualsOneOfTwo) Reset()                    { *m = EqualsOneOfTwo{} }
func (m *EqualsOneOfTwo) String() string            { return proto.CompactTextString(m) }
func (*EqualsOneOfTwo) ProtoMessage()               {}
func (*EqualsOneOfTwo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type VerifiableShuffle struct {
}

func (m *VerifiableShuffle) Reset()                    { *m = VerifiableShuffle{} }
func (m *VerifiableShuffle) String() string            { return proto.CompactTextString(m) }
func (*VerifiableShuffle) ProtoMessage()               {}
func (*VerifiableShuffle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DiscreteLogEquality struct {
	Ts [][]byte `protobuf:"bytes,1,rep,name=ts,proto3" json:"ts,omitempty"`
	R  []byte   `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogEquality) Reset()                    { *m = DiscreteLogEquality{} }
func (m *DiscreteLogEquality) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogEquality) ProtoMessage()               {}
func (*DiscreteLogEquality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*AlphaBeta)(nil), "pb.AlphaBeta")
	proto.RegisterType((*MixedOutput)(nil), "pb.MixedOutput")
	proto.RegisterType((*RandomizedOuput)(nil), "pb.RandomizedOuput")
	proto.RegisterType((*DiscreteLogKnowledge)(nil), "pb.DiscreteLogKnowledge")
	proto.RegisterType((*EqualsOneOfTwo)(nil), "pb.EqualsOneOfTwo")
	proto.RegisterType((*VerifiableShuffle)(nil), "pb.VerifiableShuffle")
	proto.RegisterType((*DiscreteLogEquality)(nil), "pb.DiscreteLogEquality")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ZKPAuction service

type ZKPAuctionClient interface {
	// Sends a key
	SendKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// TODO millionaire specific
	MillionaireAlphaBeta(ctx context.Context, in *AlphaBeta, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireGammaDelta1(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireGammaDelta2(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireRandomizeOutput(ctx context.Context, in *RandomizedOuput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type zKPAuctionClient struct {
	cc *grpc.ClientConn
}

func NewZKPAuctionClient(cc *grpc.ClientConn) ZKPAuctionClient {
	return &zKPAuctionClient{cc}
}

func (c *zKPAuctionClient) SendKey(ctx context.Context, in *Key, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/SendKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireAlphaBeta(ctx context.Context, in *AlphaBeta, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireAlphaBeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireGammaDelta1(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireGammaDelta1", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireGammaDelta2(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireGammaDelta2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireRandomizeOutput(ctx context.Context, in *RandomizedOuput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireRandomizeOutput", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZKPAuction service

type ZKPAuctionServer interface {
	// Sends a key
	SendKey(context.Context, *Key) (*google_protobuf.Empty, error)
	// TODO millionaire specific
	MillionaireAlphaBeta(context.Context, *AlphaBeta) (*google_protobuf.Empty, error)
	MillionaireGammaDelta1(context.Context, *MixedOutput) (*google_protobuf.Empty, error)
	MillionaireGammaDelta2(context.Context, *MixedOutput) (*google_protobuf.Empty, error)
	MillionaireRandomizeOutput(context.Context, *RandomizedOuput) (*google_protobuf.Empty, error)
}

func RegisterZKPAuctionServer(s *grpc.Server, srv ZKPAuctionServer) {
	s.RegisterService(&_ZKPAuction_serviceDesc, srv)
}

func _ZKPAuction_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/SendKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).SendKey(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireAlphaBeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlphaBeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireAlphaBeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireAlphaBeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireAlphaBeta(ctx, req.(*AlphaBeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireGammaDelta1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MixedOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireGammaDelta1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta1(ctx, req.(*MixedOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireGammaDelta2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MixedOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireGammaDelta2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta2(ctx, req.(*MixedOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireRandomizeOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomizedOuput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireRandomizeOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireRandomizeOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireRandomizeOutput(ctx, req.(*RandomizedOuput))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZKPAuction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ZKPAuction",
	HandlerType: (*ZKPAuctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendKey",
			Handler:    _ZKPAuction_SendKey_Handler,
		},
		{
			MethodName: "MillionaireAlphaBeta",
			Handler:    _ZKPAuction_MillionaireAlphaBeta_Handler,
		},
		{
			MethodName: "MillionaireGammaDelta1",
			Handler:    _ZKPAuction_MillionaireGammaDelta1_Handler,
		},
		{
			MethodName: "MillionaireGammaDelta2",
			Handler:    _ZKPAuction_MillionaireGammaDelta2_Handler,
		},
		{
			MethodName: "MillionaireRandomizeOutput",
			Handler:    _ZKPAuction_MillionaireRandomizeOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb1, 0x4d, 0x12, 0x98, 0x84, 0x06, 0x36, 0x21, 0xac, 0xc2, 0x25, 0xf2, 0x29, 0x02,
	0xe4, 0xc8, 0xdb, 0x07, 0x40, 0x85, 0x56, 0x3d, 0x84, 0x2a, 0xc8, 0x45, 0x1c, 0xb8, 0x44, 0xeb,
	0x78, 0x9d, 0x1a, 0x6c, 0xaf, 0xb1, 0xd7, 0x2a, 0xe6, 0x49, 0x78, 0x2e, 0x9e, 0x08, 0xed, 0x9f,
	0xfc, 0x69, 0x28, 0x48, 0xed, 0xcd, 0xf3, 0xd3, 0xec, 0x37, 0x9a, 0x6f, 0x3e, 0x03, 0xac, 0x78,
	0x96, 0x79, 0x45, 0xc9, 0x05, 0x47, 0x76, 0x11, 0x8e, 0x5f, 0xae, 0x39, 0x5f, 0xa7, 0x6c, 0xa6,
	0x48, 0x58, 0xc7, 0x33, 0x96, 0x15, 0xa2, 0xd1, 0x0d, 0xee, 0x39, 0x38, 0x73, 0xd6, 0xa0, 0xa7,
	0xe0, 0x7c, 0x63, 0x0d, 0xb6, 0x26, 0xd6, 0xb4, 0x17, 0xc8, 0x4f, 0xe4, 0x41, 0xab, 0x28, 0x39,
	0x8f, 0xb1, 0x3d, 0xb1, 0xa6, 0x5d, 0x82, 0xbd, 0x22, 0xf4, 0x4e, 0x93, 0x6a, 0x55, 0x32, 0xc1,
	0x3e, 0xf0, 0xf5, 0x3c, 0xe7, 0xd7, 0x29, 0x8b, 0xd6, 0x2c, 0xd0, 0x6d, 0x2e, 0x83, 0xc7, 0x27,
	0x69, 0x71, 0x45, 0xdf, 0x31, 0x41, 0xd1, 0x08, 0xda, 0x54, 0x16, 0x15, 0xb6, 0x26, 0xce, 0xb4,
	0x17, 0x98, 0x0a, 0x0d, 0xa1, 0x15, 0x32, 0x41, 0x2b, 0x6c, 0x2b, 0xac, 0x0b, 0xf4, 0x0a, 0xda,
	0x4a, 0xa3, 0xc2, 0xce, 0xc4, 0x99, 0x76, 0x09, 0x92, 0xb3, 0xce, 0xbe, 0xd7, 0x34, 0xad, 0x16,
	0x39, 0x5b, 0xc4, 0x9f, 0xae, 0x79, 0x60, 0x3a, 0xdc, 0xaf, 0xd0, 0xbd, 0x48, 0x7e, 0xb0, 0x68,
	0x51, 0x8b, 0xa2, 0x16, 0x72, 0xd0, 0x9a, 0x66, 0xd9, 0x6e, 0x90, 0xae, 0x24, 0x8f, 0x58, 0xba,
	0x9b, 0x64, 0x2a, 0xf4, 0x7a, 0xb3, 0x95, 0xa3, 0xb6, 0x7a, 0x2e, 0x27, 0x7d, 0x66, 0x65, 0x12,
	0x27, 0x34, 0x4c, 0xd9, 0xe5, 0x55, 0x1d, 0xc7, 0xe9, 0x76, 0xa5, 0x12, 0xfa, 0x01, 0xcd, 0x23,
	0x9e, 0x25, 0x3f, 0xe5, 0xc0, 0xfb, 0xcc, 0x9b, 0x1d, 0xac, 0xf6, 0xe2, 0xc0, 0x46, 0xb5, 0x65,
	0x22, 0x9a, 0xed, 0x7e, 0x04, 0x86, 0xb7, 0xb9, 0x8c, 0x7a, 0x60, 0x09, 0x73, 0x1e, 0x4b, 0xc8,
	0xaa, 0x54, 0x87, 0xe9, 0x05, 0x56, 0xe9, 0xfe, 0xb2, 0xe0, 0xe8, 0xa6, 0x5d, 0xa8, 0x0f, 0x0e,
	0x5d, 0xfa, 0xe6, 0x81, 0x4d, 0x7d, 0x0d, 0x88, 0x79, 0x63, 0x53, 0x22, 0x41, 0xb8, 0xf4, 0x95,
	0x0f, 0xbd, 0xc0, 0x0e, 0x7d, 0x0d, 0x08, 0x7e, 0x68, 0x80, 0xea, 0x88, 0x96, 0x3e, 0x6e, 0x69,
	0x10, 0xf9, 0x1a, 0x10, 0xdc, 0x36, 0x40, 0x75, 0x94, 0x4b, 0x1f, 0x77, 0x34, 0x28, 0x7d, 0x0d,
	0x08, 0x7e, 0x64, 0x00, 0x71, 0x07, 0xf0, 0xec, 0x2f, 0x7b, 0xdd, 0x63, 0x18, 0xdc, 0x62, 0x01,
	0x3a, 0x02, 0x5b, 0x6c, 0x7c, 0xb5, 0x45, 0x75, 0x73, 0x49, 0xf2, 0xdb, 0x06, 0xf8, 0x32, 0xff,
	0x78, 0x52, 0xaf, 0x44, 0xc2, 0x73, 0xf4, 0x06, 0x3a, 0x97, 0x2c, 0x8f, 0x64, 0x76, 0x3b, 0xd2,
	0xd3, 0x39, 0x6b, 0xc6, 0x23, 0x4f, 0x27, 0xdd, 0xdb, 0x24, 0xdd, 0x3b, 0x93, 0x49, 0x77, 0x1f,
	0xa0, 0xb7, 0x30, 0xbc, 0x48, 0xd2, 0x34, 0xe1, 0x39, 0x4d, 0x4a, 0xb6, 0xcb, 0xe9, 0x13, 0xf9,
	0x74, 0x5b, 0xfe, 0x47, 0xe0, 0x3d, 0x8c, 0xf6, 0x04, 0xce, 0xe5, 0xd1, 0x4f, 0xe5, 0x85, 0x7d,
	0xd4, 0x97, 0x12, 0x7b, 0x91, 0xbc, 0x87, 0x08, 0xb9, 0x8b, 0xc8, 0x1c, 0xc6, 0x7b, 0x22, 0xdb,
	0x7c, 0x9a, 0xff, 0x61, 0x20, 0x85, 0x0e, 0x42, 0xfb, 0x6f, 0xb1, 0xb0, 0xad, 0xc8, 0xf1, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x0d, 0x62, 0x10, 0x33, 0x04, 0x00, 0x00,
}
