// Code generated by protoc-gen-go.
// source: comm.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	comm.proto

It has these top-level messages:
	OuterStruct
	Result
	Key
	AlphaBeta
	MixedOutput
	RandomizedOutput
	DecryptionInfo
	DiscreteLogKnowledge
	EqualsOneOfTwo
	VerifiableShuffle
	DiscreteLogEquality
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OuterStruct struct {
	Clientid int32  `protobuf:"varint,1,opt,name=clientid" json:"clientid,omitempty"`
	Stepid   int32  `protobuf:"varint,2,opt,name=stepid" json:"stepid,omitempty"`
	Data     []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *OuterStruct) Reset()                    { *m = OuterStruct{} }
func (m *OuterStruct) String() string            { return proto.CompactTextString(m) }
func (*OuterStruct) ProtoMessage()               {}
func (*OuterStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OuterStruct) GetClientid() int32 {
	if m != nil {
		return m.Clientid
	}
	return 0
}

func (m *OuterStruct) GetStepid() int32 {
	if m != nil {
		return m.Stepid
	}
	return 0
}

func (m *OuterStruct) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Result struct {
	Round     int32      `protobuf:"varint,1,opt,name=round" json:"round,omitempty"`
	Key       *Key       `protobuf:"bytes,2,opt,name=Key" json:"Key,omitempty"`
	AlphaBeta *AlphaBeta `protobuf:"bytes,3,opt,name=AlphaBeta" json:"AlphaBeta,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Result) GetRound() int32 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Result) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Result) GetAlphaBeta() *AlphaBeta {
	if m != nil {
		return m.AlphaBeta
	}
	return nil
}

// The request message containing the user's name.
type Key struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Zero knowledge proof of key's logarithm
	Proof *DiscreteLogKnowledge `protobuf:"bytes,2,opt,name=proof" json:"proof,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Key) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Key) GetProof() *DiscreteLogKnowledge {
	if m != nil {
		return m.Proof
	}
	return nil
}

// TODO millionaire specific
type AlphaBeta struct {
	Alphas [][]byte          `protobuf:"bytes,1,rep,name=alphas,proto3" json:"alphas,omitempty"`
	Betas  [][]byte          `protobuf:"bytes,2,rep,name=betas,proto3" json:"betas,omitempty"`
	Proofs []*EqualsOneOfTwo `protobuf:"bytes,3,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *AlphaBeta) Reset()                    { *m = AlphaBeta{} }
func (m *AlphaBeta) String() string            { return proto.CompactTextString(m) }
func (*AlphaBeta) ProtoMessage()               {}
func (*AlphaBeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlphaBeta) GetAlphas() [][]byte {
	if m != nil {
		return m.Alphas
	}
	return nil
}

func (m *AlphaBeta) GetBetas() [][]byte {
	if m != nil {
		return m.Betas
	}
	return nil
}

func (m *AlphaBeta) GetProofs() []*EqualsOneOfTwo {
	if m != nil {
		return m.Proofs
	}
	return nil
}

// TODO millionaire specific
type MixedOutput struct {
	Gammas [][]byte           `protobuf:"bytes,1,rep,name=gammas,proto3" json:"gammas,omitempty"`
	Deltas [][]byte           `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	Proof  *VerifiableShuffle `protobuf:"bytes,3,opt,name=proof" json:"proof,omitempty"`
}

func (m *MixedOutput) Reset()                    { *m = MixedOutput{} }
func (m *MixedOutput) String() string            { return proto.CompactTextString(m) }
func (*MixedOutput) ProtoMessage()               {}
func (*MixedOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MixedOutput) GetGammas() [][]byte {
	if m != nil {
		return m.Gammas
	}
	return nil
}

func (m *MixedOutput) GetDeltas() [][]byte {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *MixedOutput) GetProof() *VerifiableShuffle {
	if m != nil {
		return m.Proof
	}
	return nil
}

// TODO millionaire specific
type RandomizedOutput struct {
	Gammas [][]byte               `protobuf:"bytes,1,rep,name=gammas,proto3" json:"gammas,omitempty"`
	Deltas [][]byte               `protobuf:"bytes,2,rep,name=deltas,proto3" json:"deltas,omitempty"`
	Proofs []*DiscreteLogEquality `protobuf:"bytes,3,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *RandomizedOutput) Reset()                    { *m = RandomizedOutput{} }
func (m *RandomizedOutput) String() string            { return proto.CompactTextString(m) }
func (*RandomizedOutput) ProtoMessage()               {}
func (*RandomizedOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RandomizedOutput) GetGammas() [][]byte {
	if m != nil {
		return m.Gammas
	}
	return nil
}

func (m *RandomizedOutput) GetDeltas() [][]byte {
	if m != nil {
		return m.Deltas
	}
	return nil
}

func (m *RandomizedOutput) GetProofs() []*DiscreteLogEquality {
	if m != nil {
		return m.Proofs
	}
	return nil
}

// TODO millionaire specific
type DecryptionInfo struct {
	Phis   [][]byte               `protobuf:"bytes,1,rep,name=phis,proto3" json:"phis,omitempty"`
	Proofs []*DiscreteLogEquality `protobuf:"bytes,2,rep,name=proofs" json:"proofs,omitempty"`
}

func (m *DecryptionInfo) Reset()                    { *m = DecryptionInfo{} }
func (m *DecryptionInfo) String() string            { return proto.CompactTextString(m) }
func (*DecryptionInfo) ProtoMessage()               {}
func (*DecryptionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DecryptionInfo) GetPhis() [][]byte {
	if m != nil {
		return m.Phis
	}
	return nil
}

func (m *DecryptionInfo) GetProofs() []*DiscreteLogEquality {
	if m != nil {
		return m.Proofs
	}
	return nil
}

type DiscreteLogKnowledge struct {
	T []byte `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	R []byte `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogKnowledge) Reset()                    { *m = DiscreteLogKnowledge{} }
func (m *DiscreteLogKnowledge) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogKnowledge) ProtoMessage()               {}
func (*DiscreteLogKnowledge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DiscreteLogKnowledge) GetT() []byte {
	if m != nil {
		return m.T
	}
	return nil
}

func (m *DiscreteLogKnowledge) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

type EqualsOneOfTwo struct {
	A_1 []byte `protobuf:"bytes,1,opt,name=a_1,json=a1,proto3" json:"a_1,omitempty"`
	A_2 []byte `protobuf:"bytes,2,opt,name=a_2,json=a2,proto3" json:"a_2,omitempty"`
	B_1 []byte `protobuf:"bytes,3,opt,name=b_1,json=b1,proto3" json:"b_1,omitempty"`
	B_2 []byte `protobuf:"bytes,4,opt,name=b_2,json=b2,proto3" json:"b_2,omitempty"`
	D_1 []byte `protobuf:"bytes,5,opt,name=d_1,json=d1,proto3" json:"d_1,omitempty"`
	D_2 []byte `protobuf:"bytes,6,opt,name=d_2,json=d2,proto3" json:"d_2,omitempty"`
	R_1 []byte `protobuf:"bytes,7,opt,name=r_1,json=r1,proto3" json:"r_1,omitempty"`
	R_2 []byte `protobuf:"bytes,8,opt,name=r_2,json=r2,proto3" json:"r_2,omitempty"`
}

func (m *EqualsOneOfTwo) Reset()                    { *m = EqualsOneOfTwo{} }
func (m *EqualsOneOfTwo) String() string            { return proto.CompactTextString(m) }
func (*EqualsOneOfTwo) ProtoMessage()               {}
func (*EqualsOneOfTwo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EqualsOneOfTwo) GetA_1() []byte {
	if m != nil {
		return m.A_1
	}
	return nil
}

func (m *EqualsOneOfTwo) GetA_2() []byte {
	if m != nil {
		return m.A_2
	}
	return nil
}

func (m *EqualsOneOfTwo) GetB_1() []byte {
	if m != nil {
		return m.B_1
	}
	return nil
}

func (m *EqualsOneOfTwo) GetB_2() []byte {
	if m != nil {
		return m.B_2
	}
	return nil
}

func (m *EqualsOneOfTwo) GetD_1() []byte {
	if m != nil {
		return m.D_1
	}
	return nil
}

func (m *EqualsOneOfTwo) GetD_2() []byte {
	if m != nil {
		return m.D_2
	}
	return nil
}

func (m *EqualsOneOfTwo) GetR_1() []byte {
	if m != nil {
		return m.R_1
	}
	return nil
}

func (m *EqualsOneOfTwo) GetR_2() []byte {
	if m != nil {
		return m.R_2
	}
	return nil
}

type VerifiableShuffle struct {
}

func (m *VerifiableShuffle) Reset()                    { *m = VerifiableShuffle{} }
func (m *VerifiableShuffle) String() string            { return proto.CompactTextString(m) }
func (*VerifiableShuffle) ProtoMessage()               {}
func (*VerifiableShuffle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DiscreteLogEquality struct {
	Ts [][]byte `protobuf:"bytes,1,rep,name=ts,proto3" json:"ts,omitempty"`
	R  []byte   `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
}

func (m *DiscreteLogEquality) Reset()                    { *m = DiscreteLogEquality{} }
func (m *DiscreteLogEquality) String() string            { return proto.CompactTextString(m) }
func (*DiscreteLogEquality) ProtoMessage()               {}
func (*DiscreteLogEquality) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *DiscreteLogEquality) GetTs() [][]byte {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *DiscreteLogEquality) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func init() {
	proto.RegisterType((*OuterStruct)(nil), "pb.OuterStruct")
	proto.RegisterType((*Result)(nil), "pb.Result")
	proto.RegisterType((*Key)(nil), "pb.Key")
	proto.RegisterType((*AlphaBeta)(nil), "pb.AlphaBeta")
	proto.RegisterType((*MixedOutput)(nil), "pb.MixedOutput")
	proto.RegisterType((*RandomizedOutput)(nil), "pb.RandomizedOutput")
	proto.RegisterType((*DecryptionInfo)(nil), "pb.DecryptionInfo")
	proto.RegisterType((*DiscreteLogKnowledge)(nil), "pb.DiscreteLogKnowledge")
	proto.RegisterType((*EqualsOneOfTwo)(nil), "pb.EqualsOneOfTwo")
	proto.RegisterType((*VerifiableShuffle)(nil), "pb.VerifiableShuffle")
	proto.RegisterType((*DiscreteLogEquality)(nil), "pb.DiscreteLogEquality")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// const _ = grpc.SupportPackageIsVersion4

// Client API for ZKPAuction service

type ZKPAuctionClient interface {
	Publish(ctx context.Context, in *Result, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// TODO millionaire specific
	MillionaireAlphaBeta(ctx context.Context, in *AlphaBeta, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireGammaDelta1(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireGammaDelta2(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireRandomizeOutput(ctx context.Context, in *RandomizedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	MillionaireDecryptionInfo(ctx context.Context, in *DecryptionInfo, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type zKPAuctionClient struct {
	cc *grpc.ClientConn
}

func NewZKPAuctionClient(cc *grpc.ClientConn) ZKPAuctionClient {
	return &zKPAuctionClient{cc}
}

func (c *zKPAuctionClient) Publish(ctx context.Context, in *Result, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/Publish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireAlphaBeta(ctx context.Context, in *AlphaBeta, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireAlphaBeta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireGammaDelta1(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireGammaDelta1", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireGammaDelta2(ctx context.Context, in *MixedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireGammaDelta2", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireRandomizeOutput(ctx context.Context, in *RandomizedOutput, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireRandomizeOutput", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zKPAuctionClient) MillionaireDecryptionInfo(ctx context.Context, in *DecryptionInfo, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/pb.ZKPAuction/MillionaireDecryptionInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ZKPAuction service

type ZKPAuctionServer interface {
	Publish(context.Context, *Result) (*google_protobuf.Empty, error)
	// TODO millionaire specific
	MillionaireAlphaBeta(context.Context, *AlphaBeta) (*google_protobuf.Empty, error)
	MillionaireGammaDelta1(context.Context, *MixedOutput) (*google_protobuf.Empty, error)
	MillionaireGammaDelta2(context.Context, *MixedOutput) (*google_protobuf.Empty, error)
	MillionaireRandomizeOutput(context.Context, *RandomizedOutput) (*google_protobuf.Empty, error)
	MillionaireDecryptionInfo(context.Context, *DecryptionInfo) (*google_protobuf.Empty, error)
}

func RegisterZKPAuctionServer(s *grpc.Server, srv ZKPAuctionServer) {
	s.RegisterService(&_ZKPAuction_serviceDesc, srv)
}

func _ZKPAuction_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Result)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).Publish(ctx, req.(*Result))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireAlphaBeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlphaBeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireAlphaBeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireAlphaBeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireAlphaBeta(ctx, req.(*AlphaBeta))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireGammaDelta1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MixedOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireGammaDelta1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta1(ctx, req.(*MixedOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireGammaDelta2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MixedOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireGammaDelta2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireGammaDelta2(ctx, req.(*MixedOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireRandomizeOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomizedOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireRandomizeOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireRandomizeOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireRandomizeOutput(ctx, req.(*RandomizedOutput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZKPAuction_MillionaireDecryptionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZKPAuctionServer).MillionaireDecryptionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ZKPAuction/MillionaireDecryptionInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZKPAuctionServer).MillionaireDecryptionInfo(ctx, req.(*DecryptionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZKPAuction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ZKPAuction",
	HandlerType: (*ZKPAuctionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _ZKPAuction_Publish_Handler,
		},
		{
			MethodName: "MillionaireAlphaBeta",
			Handler:    _ZKPAuction_MillionaireAlphaBeta_Handler,
		},
		{
			MethodName: "MillionaireGammaDelta1",
			Handler:    _ZKPAuction_MillionaireGammaDelta1_Handler,
		},
		{
			MethodName: "MillionaireGammaDelta2",
			Handler:    _ZKPAuction_MillionaireGammaDelta2_Handler,
		},
		{
			MethodName: "MillionaireRandomizeOutput",
			Handler:    _ZKPAuction_MillionaireRandomizeOutput_Handler,
		},
		{
			MethodName: "MillionaireDecryptionInfo",
			Handler:    _ZKPAuction_MillionaireDecryptionInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comm.proto",
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0xdf, 0x26, 0x6b, 0xb7, 0xf7, 0x74, 0x8c, 0xe1, 0x95, 0xd1, 0x95, 0x1b, 0x94, 0x2b,
	0x04, 0x52, 0xa6, 0x66, 0x1f, 0x00, 0x0d, 0x36, 0x4d, 0xd3, 0x36, 0x6d, 0xca, 0x18, 0x17, 0xdc,
	0x20, 0xa7, 0x71, 0x5a, 0x83, 0x13, 0x07, 0xc7, 0xd1, 0x28, 0x9f, 0x84, 0x5b, 0xbe, 0x29, 0xfe,
	0xd7, 0x36, 0x2d, 0x63, 0x82, 0xdd, 0xf9, 0x79, 0x7c, 0xf2, 0x3b, 0x39, 0xc7, 0xc7, 0x06, 0x18,
	0xf1, 0x3c, 0x0f, 0x4b, 0xc1, 0x25, 0x47, 0x5e, 0x99, 0x0c, 0x9e, 0x8f, 0x39, 0x1f, 0x33, 0xb2,
	0x6f, 0x9c, 0xa4, 0xce, 0xf6, 0x49, 0x5e, 0xca, 0xa9, 0x0d, 0x08, 0x6e, 0xa0, 0x7b, 0x59, 0x4b,
	0x22, 0xae, 0xa5, 0xa8, 0x47, 0x12, 0x0d, 0x60, 0x63, 0xc4, 0x28, 0x29, 0x24, 0x4d, 0xfb, 0xad,
	0x17, 0xad, 0x97, 0xed, 0x78, 0xae, 0xd1, 0x2e, 0x74, 0x2a, 0x49, 0x4a, 0xb5, 0xe3, 0x99, 0x1d,
	0xa7, 0x10, 0x82, 0xb5, 0x14, 0x4b, 0xdc, 0xf7, 0x95, 0xbb, 0x19, 0x9b, 0x75, 0x90, 0x41, 0x27,
	0x26, 0x55, 0xcd, 0x24, 0xea, 0x41, 0x5b, 0xf0, 0xba, 0x98, 0xe1, 0xac, 0x40, 0x7b, 0xe0, 0x9f,
	0x91, 0xa9, 0x01, 0x75, 0xa3, 0xf5, 0xb0, 0x4c, 0x42, 0x25, 0x63, 0xed, 0xa1, 0xd7, 0xf0, 0xff,
	0x21, 0x2b, 0x27, 0xf8, 0x2d, 0x71, 0xcc, 0x6e, 0xf4, 0x48, 0x07, 0xcc, 0xcd, 0x78, 0xb1, 0x1f,
	0x9c, 0x18, 0x0e, 0xda, 0x06, 0xff, 0x8b, 0xc2, 0xb5, 0xcc, 0x1f, 0xe8, 0x25, 0x0a, 0xa1, 0xad,
	0x0a, 0xe4, 0x99, 0x4b, 0xd1, 0xd7, 0x84, 0x23, 0x5a, 0x8d, 0x04, 0x91, 0xe4, 0x9c, 0x8f, 0xcf,
	0x0a, 0x7e, 0xcb, 0x48, 0x3a, 0x26, 0xb1, 0x0d, 0x0b, 0x48, 0x23, 0xab, 0xae, 0x14, 0x6b, 0x51,
	0x29, 0xa2, 0xaf, 0x88, 0x4e, 0xe9, 0x5a, 0x12, 0xb5, 0x5f, 0x29, 0xa8, 0xb6, 0xad, 0x40, 0xaf,
	0xa0, 0x63, 0x18, 0x95, 0xfa, 0x5b, 0x5f, 0xe5, 0x42, 0x3a, 0xd7, 0xf1, 0xd7, 0x1a, 0xb3, 0xea,
	0xb2, 0x20, 0x97, 0xd9, 0xfb, 0x5b, 0x1e, 0xbb, 0x88, 0xe0, 0x33, 0x74, 0x2f, 0xe8, 0x37, 0x92,
	0xaa, 0x9e, 0x97, 0xb5, 0xd4, 0x89, 0xc6, 0x38, 0xcf, 0x17, 0x89, 0xac, 0xd2, 0x7e, 0x4a, 0xd8,
	0x22, 0x93, 0x53, 0xaa, 0x37, 0xae, 0x2a, 0xdb, 0x97, 0xa7, 0x3a, 0xd3, 0x07, 0x22, 0x68, 0x46,
	0x71, 0xc2, 0xc8, 0xf5, 0xa4, 0xce, 0x32, 0x36, 0x2f, 0xa9, 0x82, 0xed, 0x18, 0x17, 0x29, 0xcf,
	0xe9, 0xf7, 0x07, 0x27, 0xdc, 0x5f, 0xa9, 0xed, 0xd9, 0x4a, 0x1f, 0x4d, 0x99, 0x54, 0x4e, 0xe7,
	0x05, 0xde, 0xc0, 0xd6, 0x11, 0x19, 0x89, 0x69, 0x29, 0x29, 0x2f, 0x4e, 0x8b, 0x8c, 0xeb, 0xf1,
	0x28, 0x27, 0x74, 0x96, 0xd0, 0xac, 0x1b, 0x58, 0xef, 0xef, 0xb0, 0x11, 0xf4, 0xee, 0x3a, 0x3d,
	0xb4, 0x09, 0x2d, 0xe9, 0x8e, 0xbd, 0x25, 0xb5, 0x12, 0xe6, 0xc0, 0x95, 0x12, 0xc1, 0x8f, 0x16,
	0x6c, 0x2d, 0x1f, 0x03, 0x7a, 0x0c, 0x3e, 0xfe, 0x34, 0x74, 0x1f, 0x78, 0x78, 0x68, 0x8d, 0xc8,
	0x7d, 0xe3, 0xe1, 0x48, 0x1b, 0x89, 0x8a, 0xb0, 0xb3, 0xec, 0x25, 0x43, 0x6b, 0x44, 0xfd, 0x35,
	0x67, 0x98, 0x88, 0x54, 0x45, 0xb4, 0xad, 0x91, 0x0e, 0xad, 0x11, 0xf5, 0x3b, 0xce, 0x30, 0x11,
	0x42, 0x45, 0xac, 0x5b, 0x43, 0x0c, 0xad, 0x11, 0xf5, 0x37, 0x9c, 0x11, 0x05, 0x3b, 0xf0, 0xe4,
	0xb7, 0x63, 0x0b, 0x0e, 0x60, 0xe7, 0x8e, 0x16, 0xa0, 0x2d, 0xf0, 0xe4, 0xac, 0x7b, 0x6a, 0xb5,
	0x5c, 0x64, 0xf4, 0xd3, 0x07, 0xf8, 0x78, 0x76, 0x75, 0xa8, 0x2e, 0xaf, 0x6a, 0xb8, 0x6a, 0xec,
	0xfa, 0x55, 0x9d, 0x30, 0x5a, 0x4d, 0x10, 0xe8, 0x9e, 0xda, 0x4b, 0x38, 0xd8, 0x0d, 0xed, 0x1b,
	0x10, 0xce, 0xde, 0x80, 0xf0, 0x58, 0xbf, 0x01, 0xc1, 0x7f, 0xe8, 0x0d, 0xf4, 0x2e, 0x28, 0x63,
	0xea, 0x5b, 0x4c, 0x05, 0x59, 0x5c, 0x81, 0xe5, 0x2b, 0x77, 0x0f, 0xe0, 0x1d, 0xec, 0x36, 0x00,
	0x27, 0x7a, 0x9c, 0x8e, 0xf4, 0xec, 0xa8, 0xaa, 0x35, 0xa2, 0x31, 0xed, 0x0f, 0x80, 0x44, 0xff,
	0x02, 0x39, 0x87, 0x41, 0x03, 0x32, 0x1f, 0x7d, 0x37, 0xf9, 0x3d, 0xd3, 0x8e, 0x95, 0xfb, 0x70,
	0x0f, 0xed, 0x14, 0xf6, 0x1a, 0xb4, 0xd5, 0x99, 0x36, 0xf3, 0xba, 0xe4, 0xfd, 0x19, 0x95, 0x74,
	0x8c, 0x73, 0xf0, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x74, 0x57, 0x60, 0x38, 0x99, 0x05, 0x00, 0x00,
}
